name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v2

    - name: 設定 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 建立 Docker 映像
      run: docker build -t yourusername/yourimage:latest .

    - name: 登入 Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 推送 Docker 映像
      run: docker push yourusername/yourimage:latest

    - name: 部署
      run: |
        # Your deployment commands here