name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v2

    - name: 部署到 Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "image-prompt-microservice"
        heroku_email: "jb22621550@gmail.com"

    - name: 設定 Heroku 環境變數
      run: |
        heroku config:set OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --app image-prompt-microservice
        heroku config:set OPENAI_MODEL=gpt-4o-mini --app image-prompt-microservice
        heroku config:set OPENAI_API_ENDPOINT=https://api.openai.com/v1/chat/completions --app image-prompt-microservice
        heroku config:set LOG_LEVEL=INFO --app image-prompt-microservice
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}